export default {
  SELECT: 'SELECT_DIARY',
  CREATE: 'CREATE_NEW_DIARY',
  BACK_EDITED: 'BACK_TO_TOP_WHEN_EDITED',
  BACK_NO_EDITED: 'BACK_TO_TOP_WHEN_NO_EDITED',
  DONE: 'EDIT_DONE',
  DELETE: 'DELETE_DIARY',
  AUTO_SAVE: 'SAVE_EDITED_DIARY_AUTOMATICALLY',
  ADD: 'ADD_NEW_DIARY_MANUALLY'
};
